hostname: query.ijmacd.com
web:
  replicaCount: 1
  repository:
    image: docker.io/ijmacd/query
  persistence:
    enabled: true
    storage_class: "local-path"
    capacity: "8Gi"
  tls:
    enabled: false
  local:
    enabled: false
